### ISSUE TITLE
A new doorstop log file is created in the Resonite root install directory each time the application is started

### ISSUE THREAD

**Issue by Nytra** [ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite#1]
This is kinda spammy and it would be nice if this didn't happen, maybe those logs could go to a separate isolated folder.

**Comment by Banane9** [comment]
Teeechnically this should go on the [MonkeyLoader](https://github.com/MonkeyModdingTroop/MonkeyLoader) repo, buuut I'm not sure how much we can do about that anyways. It's something Doorstop does automatically and there doesn't seem to be a way to change that. Could add something to delete the log files, it just wasn't really a concern so far.
