### ISSUE TITLE
Fallback to SyncMemberEditorBuilder or UIBuilder-based member editors if no official UI template exists for a certain type

### ISSUE THREAD

**Issue by Nytra** [ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite#10]
This would be good for colorX settings since there is no official UI template for those yet

**Comment by Banane9** [comment]
Since the UI for the settings feeds is completely automatically generated, there's no UIBuilder-ing involved - one would probably have to look into automatically adding the necessary templates for it to use.
I haven't looked into where that would make the most sense, or how easy that would be.

**Comment by Nytra** [comment]
I think a basic template for colorX could be added to the DataFeedItemMapper at least until the Resonite content team makes an official one

**Comment by Nytra** [comment]
Something like this maybe (but not so wide)

![2024-05-04 15 08 07](https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite/assets/14206961/daba439b-67a5-41cc-80e5-1387c4e5d090)

**Comment by Banane9** [comment]
Yea, that looks reasonable. Can probably just slap the whole color editor in there 😅

**Comment by Nytra** [comment]
I have it generated in code now but it's still so wide x3

![Screenshot 2024-05-04 191200](https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite/assets/14206961/7026d64e-8e5f-430b-ad61-49ed334be4c0)
