### ISSUE TITLE
Don't generate mod configs in worldspace

### ISSUE THREAD

**Issue by Nytra** [ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite#13]
Some mods use custom types in their configs and if these get generated in worldspace it would crash other users

If you spawn the settings from Resonite Essentials -> Facets -> Templates -> Settings, you can see that it generates the entire MonkeyLoader category in worldspace

**Comment by Banane9** [comment]
Ohhh, yea, that's not good :D

We could inject an IsLocalSpace or whatever it was check, I guess 🤔

**Comment by Nytra** [comment]
So the question is, do we want to generate the MonkeyLoader category at all in userspace? We could skip it entirely.

**Comment by Nytra** [comment]
If we do a check for the world in the Enumerate prefix, we can skip everything.

![Screenshot 2024-05-04 165829](https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite/assets/14206961/fb6e237e-36fe-44ed-a00d-dd787b7441f4)

![2024-05-04 15 58 10](https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite/assets/14206961/8f80b2df-2ec9-476e-80bb-b1a00eed5169)

**Comment by Banane9** [comment]
I think World has an IsUserspace property or such too, that would support it for other local worlds (in theory anyways).  🤔

Otherwise, I'd say make it return a message that it's not supported in sessions and it's perfect :D

**Comment by Nytra** [comment]
How is this?

![2024-05-04 16 38 32](https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite/assets/14206961/421fa1f8-2bb1-4e0b-9ffc-cbdf6ddee218)

**Comment by Banane9** [comment]
Looks good 👌
