### ISSUE TITLE
Monkey Loader settings UI broken in Beta 2024.4.24.1426

### ISSUE THREAD

**Issue by Nytra** [ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite#2]
It just shows a blank screen

[DESKTOP-H976HO2 - 2024.4.24.1426 - 2024-04-25 01_06_26.log](https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite/files/15102196/DESKTOP-H976HO2.-.2024.4.24.1426.-.2024-04-25.01_06_26.log)

**Comment by Banane9** [comment]
Ah, froox changed the DataFeedItem InitBase method, it seems. Probably added another optional argument, so probably no actual code change necessary.

**Comment by Banane9** [comment]
Yup, recompile with updated references fixed it

![grafik](https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite/assets/2124570/3cd67430-b858-4baa-8c0a-070938ce4013)

**Comment by Nytra** [comment]
Will you make a new release?
