### ISSUE TITLE
Possibly make the injected colorX template non-persistent so it doesn't get saved with the dash

### ISSUE THREAD

**Issue by Nytra** [ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite#25]
The way it works right now it could get saved with the dash, then used anywhere else where a colorX item is needed in the settings, even in other categories.

It's not a problem right now since there are no colorX items elsewhere, but could be a problem in the future if the Resonite team adds colorX settings.

**Comment by Banane9** [comment]
Oh damn, I thought you made it non persistent... Do the templates even get saved? Thought it all gets reconstructed when loaded 🤔

**Comment by Nytra** [comment]
I think the templates might get saved. Not sure how it works exactly.

**Comment by Nytra** [comment]
I'm not sure exactly how to approach this one because it's not enough to just make the slot non-persistent, we actually need to remove the mapping from the DataFeedItemMapper too :/

**Comment by Banane9** [comment]
Looked at a few logs and it always says that the template got injected, so I don't think this is an issue 👀

**Comment by Nytra** [comment]
Well you need to trigger a dash save by either adding a facet or marking changes on the Workspace component, but I have verified that our injected template does get saved if you do that.

**Comment by Banane9** [comment]
Ahhhhh, I see... that's annoying. Could add code to clean it up too, I guess?
