### ISSUE TITLE
Mod settings should be able to be taken out as facets and function

### ISSUE THREAD

**Issue by epicEaston197** [ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite#30]
### Is your feature request related to a problem? Please describe.

Currently if you grab a facet out of your settings menu from the monkey loader settings category and put it on somewhere else like your dash it doesn't function
![image](https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite/assets/76523692/336c66d5-8aea-494c-b7c7-2d404c074535)

### Describe the solution you'd like

I should be able to take mod settings out of my settings menu from the monkey loader category and be able to put them somewhere else like my dash and have them function

### Describe alternatives you've considered

None

### Additional Context

_no_response_

### Requesters

@epicEaston197

**Comment by Nytra** [comment]
Best way I can think to do this is to either patch Facet.OnAwake or Facet.OnLoading, which would run code for every facet that exists, however we can do some kind of check for if it's a config facet or not

**Comment by epicEaston197** [comment]
has this bill been publicly released yet?
