### ISSUE TITLE
Provide a save button for configs

### ISSUE THREAD

**Issue by SectOLT** [ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite#4]
Currently, save only occurs on manual shutdown of the game. 
Unexpected crashes may lead to data loss.
I would suggest adding a save button somewhere to force the save of the data locally for if ever the game decides to crash unexpectedly.

**Comment by ljoonal** [comment]
Even better, I would suggest flushing to disk basically immediately asynchronously after changes have been made, so that a save button wouldn't be necessary :stuck_out_tongue:

**Comment by Banane9** [comment]
> Even better, I would suggest flushing to disk basically immediately asynchronously after changes have been made, so that a save button wouldn't be necessary 😛

I'm not sure - a "reload saved" option to "soft reset" things may be useful too. It's like the middle ground between full reset to defaults and ... nothing xD
