### ISSUE TITLE
Can't mix enums

### ISSUE THREAD

**Issue by epicEaston197** [ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite#48]
when I was configuring the enums for [ExposePatchMethods](https://github.com/Nytra/ResoniteExposePatchedMethods) I noticed once I edited the  enum I couldn't restore its original config 

(The original config is a mix of all the enums in one)
![image](https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.ResoniteModLoader/assets/76523692/ea389610-491a-46ed-88ee-0b267e690c73)

**Comment by Banane9** [comment]
Well, it's in now anyways lol
