### ISSUE TITLE
Wrong line endings in linux script file

### ISSUE THREAD

**Issue by Shywizz** [ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite#49]
Can write a PR if needed, but as far as my limited testing goes, the script that's run in steams commandline args will not run under a linux shell with the current script

the fix is to quickly run the script through a sed script that converts the line endings, but having the download reflect that change would avoid some tweaking post-download.

script I used : 
`sed -i -e 's/\r$//' ./run_monkeyloader.sh`
Resonite Version :  `Beta 2024.7.20.1115`
Release Package Name : 
_`MonkeyLoader-v0.19.1+Resonite-v0.17.1+RML-v3.0.0.zip`_

**Comment by Banane9** [comment]
Linux is @ljoonal's specialty, but please do make a PR on the main MonkeyLoader repo: https://github.com/MonkeyModdingTroop/MonkeyLoader

**Comment by ljoonal** [comment]
huh...? On my filesystem it is listed as LF in the git repo's `master` branch;
```sh
❯ git ls-files --eol | grep run
i/lf    w/lf    attr/text=auto          MonkeyLoader/vendor/run_monkeyloader.sh
```
Perhaps something has happened to it whilst bundling, since I assume that @Banane9 creates the release zip files on a Windows machine..?
