### ISSUE TITLE
Allow mods to inject elements in arbitrary positions in the settings

### ISSUE THREAD

**Issue by Banane9** [ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite#6]
This would allow mods that add things specific to certain subsystems to inject their settings right with the settings for that subsystem, making it easier to configure in one place.

For example: allowing a mod that adds notifications to add their settings to the existing notification settings.

**Comment by ljoonal** [comment]
I assume that this should work for procedural created settings? Aka for [PrivacyShield](https://git.ljoonal.xyz/LJ-Resonite/Resonite-Mods#privacy-shield), would be neat to use the existing host networking settings UI.

**Comment by Banane9** [comment]
> I assume that this should work for procedural created settings?

Considering the data feeds are basically just a fancy enumerable, I was considering a similar system to the [EnumerableInjector](https://github.com/MonkeyModdingTroop/MonkeyLoader/blob/master/MonkeyLoader/Utility/EnumerableInjector.cs) (which really needs options for inserting extra elements too). 

Could tie in with https://github.com/MonkeyModdingTroop/MonkeyLoader/issues/9 too, to "automagically" set a setting up to appear in a specific location as well.

**Comment by ljoonal** [comment]
Mhmh, ye I can't claim to have even looked at any code in relation to the new settings :stuck_out_tongue: maybe one day....

**Comment by Banane9** [comment]
If you look at the SettingsFeedInjector, you can see what it does to do its thing - the settings basically do a similar thing just with more reflection and dynamic discovery

**Comment by Nytra** [comment]
Would have to be careful with this because those settings categories can generate outside of userspace, and if the mod adds anything like custom types to the data model it would crash other people.

**Comment by Banane9** [comment]
Yea... Perhaps we should just run it all through a filter to ensure that no none-vanilla types can be leaked out. That would fix the potential problem with the general MonkeyLoader category too 🤔

**Comment by Nytra** [comment]
But also people might not want stuff like their mod list visible in the world anyway

**Comment by Banane9** [comment]
> But also people might not want stuff like their mod list visible in the world anyway

Yea, that's true. I suppose we could make it so that the event for it transfers whether it's in userspace, and then the template monkey implementation for a handler of it just has it setup to only apply in userspace.
Can make it overridable or have an overridable property specifically for that too.
