### ISSUE TITLE
Create separate tooltip data repository

### ISSUE THREAD

**Issue by Banane9** [ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite#63]
Currently, the tooltips added by the gamepack (#60) only apply for a few buttons as examples.

The locale strings should be defined in a separate mod, which can be updated easier.
Texts may be "imported" from Psychpsyo's old Tooltippery [DefaultTooltips](https://github.com/Psychpsyo/DefaultTooltips/).

To find the required locale key and possible arguments for buttons, enable the DebugButtonData option in the Resonite Game Pack / Tooltips section

**Comment by Nytra** [comment]
Repo was created https://github.com/ResoniteModdingGroup/VanillaTooltips
