### ISSUE TITLE
Broader mesh array support

### ISSUE THREAD

**Issue by Dusty-Sprinkles** [ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite#66]
I wanted to use a beizer tube mesh and tube mesh the other day and while the tube mesh kinda loaded neither of them were properly usable

It'd be nice if they could be made into lists (as well as any other procedural meshes that may be still not fully working I didn't look at everything) so I can commit crimes with all of the weird meshes

**Comment by Banane9** [comment]
Eventually those should be moved out into a separate mod, but we'll see what is possible there 👍

**Comment by Nytra** [comment]
(reposting from discord) 

TubePoint is a struct that doesn't have any sync members, so it would be a bit tricky, although since it's just a float3 and float it might be possible to proxy it through a `ValueGradientDriver<float3>`
