### ISSUE TITLE
Toggling off the data feed injector locks user out of the MonkeyLoader settings category

### ISSUE THREAD

**Issue by Nytra** [ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite#70]
This probably shouldn't be toggleable through the UI

https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite/blob/92f84ca9f172c65a19bf8b60cee30d17d8c4c252/MonkeyLoader.Resonite.Integration/DataFeeds/DataFeedInjector.cs#L19

**Comment by Banane9** [comment]
Hmmm, in principle I like having an option to disable those in general... Guess we should exclude the option for the SettingsDataFeed?

**Comment by Banane9** [comment]
Ugh, forgot to include this
